### ISSUE TITLE
Flutter Machine Learning Custom Model

### ISSUE THREAD

**Issue by mady143** [Rishit-dagli/Face-Recognition_Flutter#7]
Hi @Rishit-dagli ,

I was very new to flutter and  developed an app that recognises the plant disease detection and i was successfully implemented with a tflite model and its working fine and i am getting the output.

But right now this mail is regarding , that I placed my model in app folder assets and load that model from their itself but i want to load the model from other sources like firebase ml custom model section though i can resize the app to 5 to 7 mb could you help me to load the model from the firebase after installing the app

Thanks and Regards,
Manikantha Sekhar,

**Comment by Rishit-dagli** [comment]
Hi @mady143 ,
Since your app uses custom TensorFlow Lite models, you can use Firebase ML to deploy your models. By deploying models with Firebase, you can reduce the initial download size of your app which you require.

## Deploying model

You would first deploy your custom TensorFlow model using either the Firebase console or the Firebase Admin Python and Node.js SDKs. See [Deploy and manage custom models](https://firebase.google.com/docs/ml/manage-hosted-models) for detailed guide.

## Download model

To use your TensorFlow Lite model in your app, first, use the Firebase ML SDK to download the latest version of the model to the device. To start the model download, call the model manager's `download()` method, specifying the name you assigned the model. (Firebase is wonderful :smiley: - model downloads happen asynchronously and you don't do the heavy lifting of updating your model versions and/ or apps).

### How to do this

You would first make a `FirebaseCustomRemoteModel` object and call the `build` method on it. To pass the conditions in which you want to download the model make a `FirebaseModelDownloadConditions` object. Finally, then you can call the `download()` method on these.

> Note: This looks like some work but  it is in fact very easy while implementing.

## TF Interpreter

Use the `getLatestModelFile()` method and use this value to instantiate a TensorFlow Lite interpreter. This would essentially be responsible for running it.

## Inference :rocket: 

I am assuming you know your model format and input/ output shapes. You would have to do these particular transformations yourself. So maybe if it's an image-based model you could generate an input `ByteBuffer` from a `Bitmap` object. You will then use TensorFlow Lite interpreter's `run()` method to do the inference.

For more details also read [Use a TensorFlow Lite model for inference with ML Kit on Android](https://firebase.google.com/docs/ml-kit/android/use-custom-models)

**Comment by Rishit-dagli** [comment]
@mady143 I am closing this issue as of now since I feel the above comment solves it, in case of any problems feel free to let me know about them. If you feel this repo was useful consider starring it, to helps me a lot.
